-- AX Scout Supabase Schema

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  mlb_team_id integer unique,
  abbreviation text not null unique,
  name text not null,
  league text,
  division text,
  created_at timestamptz default now()
);

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  mlb_player_id integer unique,
  full_name text not null,
  current_team_abbreviation text,
  bats text,
  throws text,
  position text,
  created_at timestamptz default now()
);

create table if not exists public.games (
  id bigint generated by default as identity primary key,
  mlb_game_pk integer unique,
  game_date date not null,
  home_team text not null,
  away_team text not null,
  home_score integer,
  away_score integer,
  status text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.data_refresh_runs (
  id bigint generated by default as identity primary key,
  pipeline_name text not null,
  started_at timestamptz default now(),
  finished_at timestamptz,
  status text not null check (status in ('running', 'success', 'failed')),
  source_date date,
  records_loaded integer default 0,
  error_message text,
  created_at timestamptz default now()
);

create table if not exists public.user_favorite_teams (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  team_id bigint not null references public.teams(id) on delete cascade,
  created_at timestamptz default now(),
  unique(user_id, team_id)
);

create table if not exists public.dim_teams (
  team_key bigint generated by default as identity primary key,
  mlb_team_id integer unique,
  abbreviation text not null unique,
  name text not null,
  league text,
  division text,
  created_at timestamptz default now()
);

create table if not exists public.fact_games (
  game_key bigint generated by default as identity primary key,
  mlb_game_pk integer unique,
  game_date date not null,
  home_team_key bigint references public.dim_teams(team_key),
  away_team_key bigint references public.dim_teams(team_key),
  home_score integer,
  away_score integer,
  status text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.dim_teams enable row level security;
alter table public.fact_games enable row level security;

create policy "Allow public read dim teams"
on public.dim_teams
for select
using (true);

create policy "Allow public read fact games"
on public.fact_games
for select
using (true);