-- AX Scout Supabase Schema

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  mlb_team_id integer unique,
  abbreviation text not null unique,
  name text not null,
  league text,
  division text,
  created_at timestamptz default now()
);

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  mlb_player_id integer unique,
  full_name text not null,
  current_team_abbreviation text,
  bats text,
  throws text,
  position text,
  created_at timestamptz default now()
);

create table if not exists public.games (
  id bigint generated by default as identity primary key,
  mlb_game_pk integer unique,
  game_date date not null,
  home_team text not null,
  away_team text not null,
  home_score integer,
  away_score integer,
  status text,
  home_probable_pitcher_mlb_id integer,
  home_probable_pitcher_name text,
  away_probable_pitcher_mlb_id integer,
  away_probable_pitcher_name text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.games
add column if not exists home_probable_pitcher_mlb_id integer,
add column if not exists home_probable_pitcher_name text,
add column if not exists away_probable_pitcher_mlb_id integer,
add column if not exists away_probable_pitcher_name text;

create table if not exists public.data_refresh_runs (
  id bigint generated by default as identity primary key,
  pipeline_name text not null,
  started_at timestamptz default now(),
  finished_at timestamptz,
  status text not null check (status in ('running', 'success', 'failed')),
  source_date date,
  records_loaded integer default 0,
  error_message text,
  created_at timestamptz default now()
);

create table if not exists public.user_favorite_teams (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  team_id bigint not null references public.teams(id) on delete cascade,
  created_at timestamptz default now(),
  unique(user_id, team_id)
);

create table if not exists public.dim_teams (
  team_key bigint generated by default as identity primary key,
  mlb_team_id integer unique,
  abbreviation text not null unique,
  name text not null,
  league text,
  division text,
  created_at timestamptz default now()
);

create table if not exists public.fact_games (
  game_key bigint generated by default as identity primary key,
  mlb_game_pk integer unique,
  game_date date not null,
  home_team_key bigint references public.dim_teams(team_key),
  away_team_key bigint references public.dim_teams(team_key),
  home_score integer,
  away_score integer,
  status text,
  home_probable_pitcher_mlb_id integer,
  home_probable_pitcher_name text,
  away_probable_pitcher_mlb_id integer,
  away_probable_pitcher_name text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.fact_games
add column if not exists home_probable_pitcher_mlb_id integer,
add column if not exists home_probable_pitcher_name text,
add column if not exists away_probable_pitcher_mlb_id integer,
add column if not exists away_probable_pitcher_name text;

create index if not exists fact_games_home_probable_pitcher_idx
on public.fact_games(home_probable_pitcher_mlb_id);

create index if not exists fact_games_away_probable_pitcher_idx
on public.fact_games(away_probable_pitcher_mlb_id);

alter table public.dim_teams enable row level security;
alter table public.fact_games enable row level security;

create policy "Allow public read dim teams"
on public.dim_teams
for select
using (true);

create policy "Allow public read fact games"
on public.fact_games
for select
using (true);

create table if not exists public.agg_team_daily (
  id bigint generated by default as identity primary key,
  game_date date not null,
  team_key bigint references public.dim_teams(team_key),
  team_abbreviation text not null,
  opponent_team_key bigint references public.dim_teams(team_key),
  opponent_abbreviation text not null,
  is_home boolean not null,
  games_played integer not null default 1,
  wins integer not null default 0,
  losses integer not null default 0,
  runs_scored integer,
  runs_allowed integer,
  run_differential integer,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(game_date, team_key, opponent_team_key, is_home)
);

alter table public.agg_team_daily enable row level security;

create policy "Allow public read agg team daily"
on public.agg_team_daily
for select
using (true);

alter table public.agg_team_daily
add column if not exists mlb_game_pk integer;

alter table public.agg_team_daily
drop constraint if exists agg_team_daily_game_date_team_key_opponent_team_key_is_home_key;

alter table public.agg_team_daily
add constraint agg_team_daily_mlb_game_team_key_key
unique(mlb_game_pk, team_key);

create table if not exists public.agg_team_offense_weekly (
  id bigint generated by default as identity primary key,
  season integer not null,
  week_start_date date not null,
  week_end_date date not null,
  team_abbreviation text not null,
  batting_average numeric(5, 3),
  ops numeric(5, 3),
  home_runs integer not null default 0,
  runs integer,
  avg_exit_velocity numeric(6, 2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(season, week_start_date, team_abbreviation)
);

create table if not exists public.agg_team_pitching_weekly (
  id bigint generated by default as identity primary key,
  season integer not null,
  week_start_date date not null,
  week_end_date date not null,
  team_abbreviation text not null,
  era numeric(6, 2),
  whip numeric(6, 3),
  strikeouts integer not null default 0,
  avg_pitch_speed numeric(6, 2),
  avg_spin_rate numeric(8, 2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(season, week_start_date, team_abbreviation)
);

create table if not exists public.agg_team_offense_season (
  id bigint generated by default as identity primary key,
  season integer not null,
  team_abbreviation text not null,
  plate_appearances integer,
  at_bats integer,
  hits integer,
  home_runs integer,
  walks integer,
  hit_by_pitch integer,
  sacrifice_flies integer,
  total_bases integer,
  batting_average numeric(5, 3),
  obp numeric(5, 3),
  slg numeric(5, 3),
  ops numeric(5, 3),
  runs integer,
  avg_exit_velocity numeric(6, 2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(season, team_abbreviation)
);

create table if not exists public.agg_team_pitching_season (
  id bigint generated by default as identity primary key,
  season integer not null,
  team_abbreviation text not null,
  innings_pitched numeric(8, 3),
  earned_runs integer,
  hits_allowed integer,
  walks integer,
  strikeouts integer,
  era numeric(6, 2),
  whip numeric(6, 3),
  avg_pitch_speed numeric(6, 2),
  avg_spin_rate numeric(8, 2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(season, team_abbreviation)
);

alter table public.agg_team_offense_weekly enable row level security;
alter table public.agg_team_pitching_weekly enable row level security;
alter table public.agg_team_offense_season enable row level security;
alter table public.agg_team_pitching_season enable row level security;

drop policy if exists "Allow public read team offense weekly"
on public.agg_team_offense_weekly;

create policy "Allow public read team offense weekly"
on public.agg_team_offense_weekly
for select
using (true);

drop policy if exists "Allow public read team pitching weekly"
on public.agg_team_pitching_weekly;

create policy "Allow public read team pitching weekly"
on public.agg_team_pitching_weekly
for select
using (true);

drop policy if exists "Allow public read team offense season"
on public.agg_team_offense_season;

create policy "Allow public read team offense season"
on public.agg_team_offense_season
for select
using (true);

drop policy if exists "Allow public read team pitching season"
on public.agg_team_pitching_season;

create policy "Allow public read team pitching season"
on public.agg_team_pitching_season
for select
using (true);

create table if not exists public.dim_players (
  player_key bigint generated by default as identity primary key,
  mlb_player_id integer unique,
  full_name text,
  current_team_abbreviation text,
  bats text,
  throws text,
  primary_position text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.agg_player_offense_weekly (
  id bigint generated by default as identity primary key,
  season integer not null,
  week_start_date date not null,
  week_end_date date not null,
  player_key bigint references public.dim_players(player_key),
  mlb_player_id integer,
  full_name text,
  team_abbreviation text,
  plate_appearances integer,
  at_bats integer,
  hits integer,
  home_runs integer,
  walks integer,
  strikeouts integer,
  batting_average numeric,
  obp numeric,
  slg numeric,
  ops numeric,
  avg_exit_velocity numeric,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(season, week_start_date, mlb_player_id)
);

create table if not exists public.agg_player_pitching_weekly (
  id bigint generated by default as identity primary key,
  season integer not null,
  week_start_date date not null,
  week_end_date date not null,
  player_key bigint references public.dim_players(player_key),
  mlb_player_id integer,
  full_name text,
  team_abbreviation text,
  batters_faced integer,
  strikeouts integer,
  walks integer,
  hits_allowed integer,
  home_runs_allowed integer,
  avg_pitch_speed numeric,
  avg_spin_rate numeric,
  era numeric,
  whip numeric,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(season, week_start_date, mlb_player_id)
);

create table if not exists public.agg_player_offense_season (
  id bigint generated by default as identity primary key,
  season integer not null,
  player_key bigint references public.dim_players(player_key),
  mlb_player_id integer,
  full_name text,
  team_abbreviation text,
  plate_appearances integer,
  at_bats integer,
  hits integer,
  home_runs integer,
  walks integer,
  strikeouts integer,
  batting_average numeric,
  obp numeric,
  slg numeric,
  ops numeric,
  avg_exit_velocity numeric,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(season, mlb_player_id)
);

create table if not exists public.agg_player_pitching_season (
  id bigint generated by default as identity primary key,
  season integer not null,
  player_key bigint references public.dim_players(player_key),
  mlb_player_id integer,
  full_name text,
  team_abbreviation text,
  batters_faced integer,
  strikeouts integer,
  walks integer,
  hits_allowed integer,
  home_runs_allowed integer,
  avg_pitch_speed numeric,
  avg_spin_rate numeric,
  era numeric,
  whip numeric,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(season, mlb_player_id)
);

create table if not exists public.agg_player_offense_rolling_7 (
  id bigint generated by default as identity primary key,
  season integer not null,
  window_start_date date not null,
  window_end_date date not null,
  player_key bigint references public.dim_players(player_key),
  mlb_player_id integer not null,
  full_name text,
  team_abbreviation text not null,
  plate_appearances integer,
  at_bats integer,
  hits integer,
  home_runs integer,
  walks integer,
  strikeouts integer,
  batting_average numeric,
  obp numeric,
  slg numeric,
  ops numeric,
  avg_exit_velocity numeric,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(season, window_end_date, team_abbreviation, mlb_player_id)
);

create table if not exists public.agg_player_pitching_rolling_7 (
  id bigint generated by default as identity primary key,
  season integer not null,
  window_start_date date not null,
  window_end_date date not null,
  player_key bigint references public.dim_players(player_key),
  mlb_player_id integer not null,
  full_name text,
  team_abbreviation text not null,
  batters_faced integer,
  innings_pitched numeric,
  earned_runs integer,
  hits_allowed integer,
  walks integer,
  strikeouts integer,
  home_runs_allowed integer,
  era numeric,
  whip numeric,
  avg_pitch_speed numeric,
  avg_spin_rate numeric,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(season, window_end_date, team_abbreviation, mlb_player_id)
);

create index if not exists player_offense_rolling_7_team_idx
on public.agg_player_offense_rolling_7(team_abbreviation);
create index if not exists player_offense_rolling_7_player_idx
on public.agg_player_offense_rolling_7(mlb_player_id);
create index if not exists player_offense_rolling_7_end_date_idx
on public.agg_player_offense_rolling_7(window_end_date);
create index if not exists player_offense_rolling_7_lookup_idx
on public.agg_player_offense_rolling_7(season, team_abbreviation, window_end_date);

create index if not exists player_pitching_rolling_7_team_idx
on public.agg_player_pitching_rolling_7(team_abbreviation);
create index if not exists player_pitching_rolling_7_player_idx
on public.agg_player_pitching_rolling_7(mlb_player_id);
create index if not exists player_pitching_rolling_7_end_date_idx
on public.agg_player_pitching_rolling_7(window_end_date);
create index if not exists player_pitching_rolling_7_lookup_idx
on public.agg_player_pitching_rolling_7(season, team_abbreviation, window_end_date);

alter table public.dim_players enable row level security;
alter table public.agg_player_offense_weekly enable row level security;
alter table public.agg_player_pitching_weekly enable row level security;
alter table public.agg_player_offense_season enable row level security;
alter table public.agg_player_pitching_season enable row level security;
alter table public.agg_player_offense_rolling_7 enable row level security;
alter table public.agg_player_pitching_rolling_7 enable row level security;

drop policy if exists "Allow public read dim players"
on public.dim_players;

create policy "Allow public read dim players"
on public.dim_players
for select
using (true);

drop policy if exists "Allow public read player offense weekly"
on public.agg_player_offense_weekly;

create policy "Allow public read player offense weekly"
on public.agg_player_offense_weekly
for select
using (true);

drop policy if exists "Allow public read player pitching weekly"
on public.agg_player_pitching_weekly;

create policy "Allow public read player pitching weekly"
on public.agg_player_pitching_weekly
for select
using (true);

drop policy if exists "Allow public read player offense season"
on public.agg_player_offense_season;

create policy "Allow public read player offense season"
on public.agg_player_offense_season
for select
using (true);

drop policy if exists "Allow public read player pitching season"
on public.agg_player_pitching_season;

create policy "Allow public read player pitching season"
on public.agg_player_pitching_season
for select
using (true);

drop policy if exists "Allow public read player offense rolling 7"
on public.agg_player_offense_rolling_7;

create policy "Allow public read player offense rolling 7"
on public.agg_player_offense_rolling_7
for select
using (true);

drop policy if exists "Allow public read player pitching rolling 7"
on public.agg_player_pitching_rolling_7;

create policy "Allow public read player pitching rolling 7"
on public.agg_player_pitching_rolling_7
for select
using (true);
