-- AX Scout Supabase Schema

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  mlb_team_id integer unique,
  abbreviation text not null unique,
  name text not null,
  league text,
  division text,
  created_at timestamptz default now()
);

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  mlb_player_id integer unique,
  full_name text not null,
  current_team_abbreviation text,
  bats text,
  throws text,
  position text,
  created_at timestamptz default now()
);

create table if not exists public.games (
  id bigint generated by default as identity primary key,
  mlb_game_pk integer unique,
  game_date date not null,
  home_team text not null,
  away_team text not null,
  home_score integer,
  away_score integer,
  status text,
  home_probable_pitcher_mlb_id integer,
  home_probable_pitcher_name text,
  away_probable_pitcher_mlb_id integer,
  away_probable_pitcher_name text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.games
add column if not exists home_probable_pitcher_mlb_id integer,
add column if not exists home_probable_pitcher_name text,
add column if not exists away_probable_pitcher_mlb_id integer,
add column if not exists away_probable_pitcher_name text;

create table if not exists public.data_refresh_runs (
  id bigint generated by default as identity primary key,
  pipeline_name text not null,
  started_at timestamptz default now(),
  finished_at timestamptz,
  status text not null check (status in ('running', 'success', 'failed')),
  source_date date,
  records_loaded integer default 0,
  error_message text,
  created_at timestamptz default now()
);

create table if not exists public.user_favorite_teams (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  team_id bigint not null references public.teams(id) on delete cascade,
  created_at timestamptz default now(),
  unique(user_id, team_id)
);

create table if not exists public.dim_teams (
  team_key bigint generated by default as identity primary key,
  mlb_team_id integer unique,
  abbreviation text not null unique,
  name text not null,
  league text,
  division text,
  created_at timestamptz default now()
);

create table if not exists public.fact_games (
  game_key bigint generated by default as identity primary key,
  mlb_game_pk integer unique,
  game_date date not null,
  home_team_key bigint references public.dim_teams(team_key),
  away_team_key bigint references public.dim_teams(team_key),
  home_score integer,
  away_score integer,
  status text,
  home_probable_pitcher_mlb_id integer,
  home_probable_pitcher_name text,
  away_probable_pitcher_mlb_id integer,
  away_probable_pitcher_name text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.fact_games
add column if not exists home_probable_pitcher_mlb_id integer,
add column if not exists home_probable_pitcher_name text,
add column if not exists away_probable_pitcher_mlb_id integer,
add column if not exists away_probable_pitcher_name text;

create index if not exists fact_games_home_probable_pitcher_idx
on public.fact_games(home_probable_pitcher_mlb_id);

create index if not exists fact_games_away_probable_pitcher_idx
on public.fact_games(away_probable_pitcher_mlb_id);

create table if not exists public.odds_snapshots (
  id bigint generated by default as identity primary key,
  mlb_game_pk bigint,
  commence_time timestamptz not null,
  home_team text not null,
  away_team text not null,
  sportsbook text not null,
  market_key text not null check (market_key in ('h2h', 'spreads', 'totals')),
  market_last_update timestamptz,
  home_price numeric(12, 4),
  away_price numeric(12, 4),
  home_point numeric(8, 3),
  away_point numeric(8, 3),
  total_point numeric(8, 3),
  over_price numeric(12, 4),
  under_price numeric(12, 4),
  odds_format text not null default 'american'
    check (odds_format in ('american', 'decimal')),
  raw_event_id text not null,
  source text not null default 'the_odds_api',
  snapshot_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(raw_event_id, sportsbook, market_key, snapshot_at)
);

create index if not exists odds_snapshots_game_idx
on public.odds_snapshots(mlb_game_pk);
create index if not exists odds_snapshots_commence_time_idx
on public.odds_snapshots(commence_time);
create index if not exists odds_snapshots_home_team_idx
on public.odds_snapshots(home_team);
create index if not exists odds_snapshots_away_team_idx
on public.odds_snapshots(away_team);
create index if not exists odds_snapshots_sportsbook_idx
on public.odds_snapshots(sportsbook);
create index if not exists odds_snapshots_market_idx
on public.odds_snapshots(market_key);
create index if not exists odds_snapshots_snapshot_at_idx
on public.odds_snapshots(snapshot_at);
create index if not exists odds_snapshots_matchup_idx
on public.odds_snapshots(commence_time, home_team, away_team);

alter table public.odds_snapshots enable row level security;

drop policy if exists "Allow public read odds snapshots"
on public.odds_snapshots;

create policy "Allow public read odds snapshots"
on public.odds_snapshots
for select
using (true);

create table if not exists public.game_predictions (
  id bigint generated by default as identity primary key,
  mlb_game_pk bigint not null,
  game_date date not null,
  home_team text not null,
  away_team text not null,
  predicted_winner text,
  predicted_loser text,
  home_win_probability numeric(6, 5),
  away_win_probability numeric(6, 5),
  confidence text check (confidence in ('Low', 'Medium', 'High')),
  confidence_score numeric(6, 2),
  axscout_lean text,
  market_favorite text,
  market_sportsbook text,
  market_home_moneyline integer,
  market_away_moneyline integer,
  implied_home_probability numeric(6, 5),
  implied_away_probability numeric(6, 5),
  edge_summary text,
  explanation text,
  model_name text not null default 'rules_based_v1',
  model_version text not null default '0.1.0',
  prediction_status text not null default 'active',
  source_snapshot_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(mlb_game_pk, model_name, model_version)
);

create index if not exists game_predictions_game_idx
on public.game_predictions(mlb_game_pk);
create index if not exists game_predictions_date_idx
on public.game_predictions(game_date);
create index if not exists game_predictions_home_team_idx
on public.game_predictions(home_team);
create index if not exists game_predictions_away_team_idx
on public.game_predictions(away_team);
create index if not exists game_predictions_winner_idx
on public.game_predictions(predicted_winner);
create index if not exists game_predictions_model_idx
on public.game_predictions(model_name);
create index if not exists game_predictions_created_idx
on public.game_predictions(created_at);

alter table public.game_predictions enable row level security;

drop policy if exists "Allow public read game predictions"
on public.game_predictions;

create policy "Allow public read game predictions"
on public.game_predictions
for select
using (true);

create table if not exists public.prediction_results (
  id bigint generated by default as identity primary key,
  mlb_game_pk bigint not null,
  game_date date not null,
  home_team text not null,
  away_team text not null,
  home_score integer,
  away_score integer,
  actual_winner text,
  actual_loser text,
  predicted_winner text,
  predicted_loser text,
  prediction_correct boolean,
  home_win_probability numeric(6, 5),
  away_win_probability numeric(6, 5),
  confidence text,
  confidence_score numeric(6, 2),
  axscout_lean text,
  market_favorite text,
  market_home_moneyline integer,
  market_away_moneyline integer,
  implied_home_probability numeric(6, 5),
  implied_away_probability numeric(6, 5),
  edge_summary text,
  model_name text not null,
  model_version text not null,
  prediction_created_at timestamptz,
  scored_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(mlb_game_pk, model_name, model_version)
);

create index if not exists prediction_results_game_idx
on public.prediction_results(mlb_game_pk);
create index if not exists prediction_results_date_idx
on public.prediction_results(game_date);
create index if not exists prediction_results_model_idx
on public.prediction_results(model_name);
create index if not exists prediction_results_version_idx
on public.prediction_results(model_version);
create index if not exists prediction_results_correct_idx
on public.prediction_results(prediction_correct);
create index if not exists prediction_results_confidence_idx
on public.prediction_results(confidence);
create index if not exists prediction_results_scored_idx
on public.prediction_results(scored_at);

alter table public.prediction_results enable row level security;

drop policy if exists "Allow public read prediction results"
on public.prediction_results;

create policy "Allow public read prediction results"
on public.prediction_results
for select
using (true);

alter table public.dim_teams enable row level security;
alter table public.fact_games enable row level security;

create policy "Allow public read dim teams"
on public.dim_teams
for select
using (true);

create policy "Allow public read fact games"
on public.fact_games
for select
using (true);

create table if not exists public.agg_team_daily (
  id bigint generated by default as identity primary key,
  game_date date not null,
  team_key bigint references public.dim_teams(team_key),
  team_abbreviation text not null,
  opponent_team_key bigint references public.dim_teams(team_key),
  opponent_abbreviation text not null,
  is_home boolean not null,
  games_played integer not null default 1,
  wins integer not null default 0,
  losses integer not null default 0,
  runs_scored integer,
  runs_allowed integer,
  run_differential integer,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(game_date, team_key, opponent_team_key, is_home)
);

alter table public.agg_team_daily enable row level security;

create policy "Allow public read agg team daily"
on public.agg_team_daily
for select
using (true);

alter table public.agg_team_daily
add column if not exists mlb_game_pk integer;

alter table public.agg_team_daily
drop constraint if exists agg_team_daily_game_date_team_key_opponent_team_key_is_home_key;

alter table public.agg_team_daily
add constraint agg_team_daily_mlb_game_team_key_key
unique(mlb_game_pk, team_key);

create table if not exists public.agg_team_offense_weekly (
  id bigint generated by default as identity primary key,
  season integer not null,
  week_start_date date not null,
  week_end_date date not null,
  team_abbreviation text not null,
  batting_average numeric(5, 3),
  ops numeric(5, 3),
  home_runs integer not null default 0,
  runs integer,
  avg_exit_velocity numeric(6, 2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(season, week_start_date, team_abbreviation)
);

create table if not exists public.agg_team_pitching_weekly (
  id bigint generated by default as identity primary key,
  season integer not null,
  week_start_date date not null,
  week_end_date date not null,
  team_abbreviation text not null,
  era numeric(6, 2),
  whip numeric(6, 3),
  strikeouts integer not null default 0,
  avg_pitch_speed numeric(6, 2),
  avg_spin_rate numeric(8, 2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(season, week_start_date, team_abbreviation)
);

create table if not exists public.agg_team_offense_season (
  id bigint generated by default as identity primary key,
  season integer not null,
  team_abbreviation text not null,
  plate_appearances integer,
  at_bats integer,
  hits integer,
  home_runs integer,
  walks integer,
  hit_by_pitch integer,
  sacrifice_flies integer,
  total_bases integer,
  batting_average numeric(5, 3),
  obp numeric(5, 3),
  slg numeric(5, 3),
  ops numeric(5, 3),
  runs integer,
  avg_exit_velocity numeric(6, 2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(season, team_abbreviation)
);

create table if not exists public.agg_team_pitching_season (
  id bigint generated by default as identity primary key,
  season integer not null,
  team_abbreviation text not null,
  innings_pitched numeric(8, 3),
  earned_runs integer,
  hits_allowed integer,
  walks integer,
  strikeouts integer,
  era numeric(6, 2),
  whip numeric(6, 3),
  avg_pitch_speed numeric(6, 2),
  avg_spin_rate numeric(8, 2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(season, team_abbreviation)
);

create table if not exists public.agg_team_offense_rolling_7 (
  id bigint generated by default as identity primary key,
  season integer not null,
  window_start_date date not null,
  window_end_date date not null,
  team_abbreviation text not null,
  plate_appearances integer,
  at_bats integer,
  hits integer,
  home_runs integer,
  walks integer,
  strikeouts integer,
  runs integer,
  batting_average numeric(5, 3),
  obp numeric(5, 3),
  slg numeric(5, 3),
  ops numeric(5, 3),
  avg_exit_velocity numeric(6, 2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(season, window_end_date, team_abbreviation)
);

create table if not exists public.agg_team_pitching_rolling_7 (
  id bigint generated by default as identity primary key,
  season integer not null,
  window_start_date date not null,
  window_end_date date not null,
  team_abbreviation text not null,
  batters_faced integer,
  innings_pitched numeric(8, 3),
  earned_runs integer,
  hits_allowed integer,
  walks integer,
  strikeouts integer,
  home_runs_allowed integer,
  era numeric(6, 2),
  whip numeric(6, 3),
  avg_pitch_speed numeric(6, 2),
  avg_spin_rate numeric(8, 2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(season, window_end_date, team_abbreviation)
);

create index if not exists team_offense_rolling_7_team_idx
on public.agg_team_offense_rolling_7(team_abbreviation);
create index if not exists team_offense_rolling_7_end_date_idx
on public.agg_team_offense_rolling_7(window_end_date);
create index if not exists team_offense_rolling_7_lookup_idx
on public.agg_team_offense_rolling_7(
  season,
  team_abbreviation,
  window_end_date
);

create index if not exists team_pitching_rolling_7_team_idx
on public.agg_team_pitching_rolling_7(team_abbreviation);
create index if not exists team_pitching_rolling_7_end_date_idx
on public.agg_team_pitching_rolling_7(window_end_date);
create index if not exists team_pitching_rolling_7_lookup_idx
on public.agg_team_pitching_rolling_7(
  season,
  team_abbreviation,
  window_end_date
);

alter table public.agg_team_offense_weekly enable row level security;
alter table public.agg_team_pitching_weekly enable row level security;
alter table public.agg_team_offense_season enable row level security;
alter table public.agg_team_pitching_season enable row level security;
alter table public.agg_team_offense_rolling_7 enable row level security;
alter table public.agg_team_pitching_rolling_7 enable row level security;

drop policy if exists "Allow public read team offense weekly"
on public.agg_team_offense_weekly;

create policy "Allow public read team offense weekly"
on public.agg_team_offense_weekly
for select
using (true);

drop policy if exists "Allow public read team pitching weekly"
on public.agg_team_pitching_weekly;

create policy "Allow public read team pitching weekly"
on public.agg_team_pitching_weekly
for select
using (true);

drop policy if exists "Allow public read team offense season"
on public.agg_team_offense_season;

create policy "Allow public read team offense season"
on public.agg_team_offense_season
for select
using (true);

drop policy if exists "Allow public read team pitching season"
on public.agg_team_pitching_season;

create policy "Allow public read team pitching season"
on public.agg_team_pitching_season
for select
using (true);

drop policy if exists "Allow public read team offense rolling 7"
on public.agg_team_offense_rolling_7;

create policy "Allow public read team offense rolling 7"
on public.agg_team_offense_rolling_7
for select
using (true);

drop policy if exists "Allow public read team pitching rolling 7"
on public.agg_team_pitching_rolling_7;

create policy "Allow public read team pitching rolling 7"
on public.agg_team_pitching_rolling_7
for select
using (true);

create table if not exists public.dim_players (
  player_key bigint generated by default as identity primary key,
  mlb_player_id integer unique,
  full_name text,
  current_team_abbreviation text,
  bats text,
  throws text,
  primary_position text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.agg_player_offense_weekly (
  id bigint generated by default as identity primary key,
  season integer not null,
  week_start_date date not null,
  week_end_date date not null,
  player_key bigint references public.dim_players(player_key),
  mlb_player_id integer,
  full_name text,
  team_abbreviation text,
  plate_appearances integer,
  at_bats integer,
  hits integer,
  home_runs integer,
  walks integer,
  strikeouts integer,
  batting_average numeric,
  obp numeric,
  slg numeric,
  ops numeric,
  avg_exit_velocity numeric,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(season, week_start_date, mlb_player_id)
);

create table if not exists public.agg_player_pitching_weekly (
  id bigint generated by default as identity primary key,
  season integer not null,
  week_start_date date not null,
  week_end_date date not null,
  player_key bigint references public.dim_players(player_key),
  mlb_player_id integer,
  full_name text,
  team_abbreviation text,
  batters_faced integer,
  strikeouts integer,
  walks integer,
  hits_allowed integer,
  home_runs_allowed integer,
  avg_pitch_speed numeric,
  avg_spin_rate numeric,
  era numeric,
  whip numeric,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(season, week_start_date, mlb_player_id)
);

create table if not exists public.agg_player_offense_season (
  id bigint generated by default as identity primary key,
  season integer not null,
  player_key bigint references public.dim_players(player_key),
  mlb_player_id integer,
  full_name text,
  team_abbreviation text,
  plate_appearances integer,
  at_bats integer,
  hits integer,
  home_runs integer,
  walks integer,
  strikeouts integer,
  batting_average numeric,
  obp numeric,
  slg numeric,
  ops numeric,
  avg_exit_velocity numeric,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(season, mlb_player_id)
);

create table if not exists public.agg_player_pitching_season (
  id bigint generated by default as identity primary key,
  season integer not null,
  player_key bigint references public.dim_players(player_key),
  mlb_player_id integer,
  full_name text,
  team_abbreviation text,
  batters_faced integer,
  strikeouts integer,
  walks integer,
  hits_allowed integer,
  home_runs_allowed integer,
  avg_pitch_speed numeric,
  avg_spin_rate numeric,
  era numeric,
  whip numeric,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(season, mlb_player_id)
);

create table if not exists public.agg_player_offense_rolling_7 (
  id bigint generated by default as identity primary key,
  season integer not null,
  window_start_date date not null,
  window_end_date date not null,
  player_key bigint references public.dim_players(player_key),
  mlb_player_id integer not null,
  full_name text,
  team_abbreviation text not null,
  plate_appearances integer,
  at_bats integer,
  hits integer,
  home_runs integer,
  walks integer,
  strikeouts integer,
  batting_average numeric,
  obp numeric,
  slg numeric,
  ops numeric,
  avg_exit_velocity numeric,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(season, window_end_date, team_abbreviation, mlb_player_id)
);

create table if not exists public.agg_player_pitching_rolling_7 (
  id bigint generated by default as identity primary key,
  season integer not null,
  window_start_date date not null,
  window_end_date date not null,
  player_key bigint references public.dim_players(player_key),
  mlb_player_id integer not null,
  full_name text,
  team_abbreviation text not null,
  batters_faced integer,
  innings_pitched numeric,
  earned_runs integer,
  hits_allowed integer,
  walks integer,
  strikeouts integer,
  home_runs_allowed integer,
  era numeric,
  whip numeric,
  avg_pitch_speed numeric,
  avg_spin_rate numeric,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(season, window_end_date, team_abbreviation, mlb_player_id)
);

create table if not exists public.player_injuries (
  id bigint generated by default as identity primary key,
  injury_key text not null unique,
  season integer not null,
  team_abbreviation text not null,
  mlb_player_id integer,
  player_name text not null,
  primary_position text,
  status text,
  injury_description text,
  injury_type text,
  injured_list_designation text,
  date_placed date,
  expected_return text,
  source text,
  source_last_updated timestamptz,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(season, team_abbreviation, mlb_player_id, injury_description)
);

create index if not exists player_injuries_team_idx
on public.player_injuries(team_abbreviation);
create index if not exists player_injuries_player_idx
on public.player_injuries(mlb_player_id);
create index if not exists player_injuries_season_idx
on public.player_injuries(season);
create index if not exists player_injuries_active_idx
on public.player_injuries(is_active);
create index if not exists player_injuries_active_team_idx
on public.player_injuries(season, team_abbreviation, is_active);

create index if not exists player_offense_rolling_7_team_idx
on public.agg_player_offense_rolling_7(team_abbreviation);
create index if not exists player_offense_rolling_7_player_idx
on public.agg_player_offense_rolling_7(mlb_player_id);
create index if not exists player_offense_rolling_7_end_date_idx
on public.agg_player_offense_rolling_7(window_end_date);
create index if not exists player_offense_rolling_7_lookup_idx
on public.agg_player_offense_rolling_7(season, team_abbreviation, window_end_date);

create index if not exists player_pitching_rolling_7_team_idx
on public.agg_player_pitching_rolling_7(team_abbreviation);
create index if not exists player_pitching_rolling_7_player_idx
on public.agg_player_pitching_rolling_7(mlb_player_id);
create index if not exists player_pitching_rolling_7_end_date_idx
on public.agg_player_pitching_rolling_7(window_end_date);
create index if not exists player_pitching_rolling_7_lookup_idx
on public.agg_player_pitching_rolling_7(season, team_abbreviation, window_end_date);

alter table public.dim_players enable row level security;
alter table public.agg_player_offense_weekly enable row level security;
alter table public.agg_player_pitching_weekly enable row level security;
alter table public.agg_player_offense_season enable row level security;
alter table public.agg_player_pitching_season enable row level security;
alter table public.agg_player_offense_rolling_7 enable row level security;
alter table public.agg_player_pitching_rolling_7 enable row level security;
alter table public.player_injuries enable row level security;

drop policy if exists "Allow public read dim players"
on public.dim_players;

create policy "Allow public read dim players"
on public.dim_players
for select
using (true);

drop policy if exists "Allow public read player offense weekly"
on public.agg_player_offense_weekly;

create policy "Allow public read player offense weekly"
on public.agg_player_offense_weekly
for select
using (true);

drop policy if exists "Allow public read player pitching weekly"
on public.agg_player_pitching_weekly;

create policy "Allow public read player pitching weekly"
on public.agg_player_pitching_weekly
for select
using (true);

drop policy if exists "Allow public read player offense season"
on public.agg_player_offense_season;

create policy "Allow public read player offense season"
on public.agg_player_offense_season
for select
using (true);

drop policy if exists "Allow public read player pitching season"
on public.agg_player_pitching_season;

create policy "Allow public read player pitching season"
on public.agg_player_pitching_season
for select
using (true);

drop policy if exists "Allow public read player offense rolling 7"
on public.agg_player_offense_rolling_7;

create policy "Allow public read player offense rolling 7"
on public.agg_player_offense_rolling_7
for select
using (true);

drop policy if exists "Allow public read player pitching rolling 7"
on public.agg_player_pitching_rolling_7;

create policy "Allow public read player pitching rolling 7"
on public.agg_player_pitching_rolling_7
for select
using (true);

drop policy if exists "Allow public read player injuries"
on public.player_injuries;

create policy "Allow public read player injuries"
on public.player_injuries
for select
using (true);

-- Pitcher archetype analytics (Phase 1A). Pitch-level Statcast data is
-- aggregated in the pipeline and is not persisted in Supabase.
create table if not exists public.pitcher_pitch_profiles (
  id uuid primary key default gen_random_uuid(),
  mlb_player_id integer not null references public.dim_players(mlb_player_id),
  season integer not null,
  period_start date not null,
  period_end date not null,
  pitch_type text not null,
  pitch_name text,
  pitch_count integer not null check (pitch_count >= 0),
  usage_rate numeric check (usage_rate between 0 and 1),
  avg_velocity numeric,
  velocity_stddev numeric,
  velocity_p90 numeric,
  avg_spin_rate numeric,
  avg_spin_axis numeric,
  avg_ivb numeric,
  avg_horizontal_break numeric,
  avg_vaa numeric,
  avg_haa numeric,
  avg_release_height numeric,
  avg_release_side numeric,
  avg_extension numeric,
  zone_rate numeric,
  chase_rate numeric,
  whiff_rate numeric,
  csw_rate numeric,
  ground_ball_rate numeric,
  hard_hit_rate numeric,
  barrel_rate numeric,
  xwoba_allowed numeric,
  feature_version text not null default 'pitcher_features_v1',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(season, period_start, period_end, mlb_player_id, pitch_type, feature_version)
);

create table if not exists public.pitcher_archetypes (
  archetype_id uuid primary key default gen_random_uuid(),
  archetype_name text not null,
  archetype_slug text not null,
  short_description text,
  long_description text,
  season integer not null,
  cluster_number integer not null,
  algorithm text not null,
  model_version text not null,
  feature_version text not null,
  pitcher_count integer check (pitcher_count >= 0),
  representative_mlb_player_id integer references public.dim_players(mlb_player_id),
  silhouette_score numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(archetype_slug, season, model_version),
  unique(season, model_version, cluster_number)
);

create table if not exists public.pitcher_profiles (
  id uuid primary key default gen_random_uuid(),
  mlb_player_id integer not null references public.dim_players(mlb_player_id),
  season integer not null,
  period_start date not null,
  period_end date not null,
  total_pitches integer check (total_pitches >= 0),
  batters_faced integer check (batters_faced >= 0),
  starter_share numeric check (starter_share between 0 and 1),
  primary_pitch_type text,
  primary_pitch_usage numeric,
  secondary_pitch_type text,
  secondary_pitch_usage numeric,
  pitch_type_count integer,
  fastball_velocity numeric,
  fastball_family_usage numeric,
  breaking_ball_usage numeric,
  offspeed_usage numeric,
  arsenal_velocity_spread numeric,
  primary_secondary_velocity_difference numeric,
  horizontal_movement_range numeric,
  vertical_movement_range numeric,
  pitch_mix_entropy numeric,
  overall_whiff_rate numeric,
  overall_csw_rate numeric,
  overall_xwoba_allowed numeric,
  primary_archetype_id uuid,
  archetype_probability numeric check (archetype_probability between 0 and 1),
  outlier_score numeric,
  map_x numeric,
  map_y numeric,
  feature_version text not null default 'pitcher_features_v1',
  model_version text,
  refreshed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(season, period_start, period_end, mlb_player_id, feature_version)
);

create table if not exists public.pitcher_archetype_memberships (
  id uuid primary key default gen_random_uuid(),
  mlb_player_id integer not null references public.dim_players(mlb_player_id),
  archetype_id uuid not null references public.pitcher_archetypes(archetype_id) on delete cascade,
  season integer not null,
  period_start date not null,
  period_end date not null,
  membership_probability numeric check (membership_probability between 0 and 1),
  cluster_distance numeric,
  is_primary boolean not null default false,
  membership_rank integer,
  model_version text not null,
  feature_version text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(mlb_player_id, archetype_id, season, period_start, period_end, model_version)
);

create table if not exists public.pitcher_archetype_features (
  id uuid primary key default gen_random_uuid(),
  archetype_id uuid not null references public.pitcher_archetypes(archetype_id) on delete cascade,
  feature_name text not null,
  feature_mean numeric,
  feature_stddev numeric,
  league_percentile numeric check (league_percentile between 0 and 1),
  importance_rank integer,
  model_version text not null,
  feature_version text not null,
  created_at timestamptz not null default now(),
  unique(archetype_id, feature_name, model_version)
);

create table if not exists public.pitcher_similarities (
  id uuid primary key default gen_random_uuid(),
  mlb_player_id integer not null references public.dim_players(mlb_player_id),
  similar_mlb_player_id integer not null references public.dim_players(mlb_player_id),
  season integer not null,
  similarity_score numeric not null check (similarity_score between 0 and 1),
  feature_distance numeric,
  same_archetype boolean,
  similarity_rank integer,
  similarity_explanation text,
  model_version text not null,
  feature_version text not null,
  calculated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  check (mlb_player_id <> similar_mlb_player_id),
  unique(mlb_player_id, similar_mlb_player_id, season, model_version)
);

create table if not exists public.pitcher_model_runs (
  model_run_id uuid primary key default gen_random_uuid(),
  model_name text not null default 'pitcher_archetypes',
  model_version text not null,
  model_type text not null default 'unsupervised_clustering',
  season integer,
  training_start_date date,
  training_end_date date,
  algorithm text,
  feature_version text,
  parameters jsonb,
  silhouette_score numeric,
  cluster_count integer,
  pitcher_count integer,
  status text not null check (status in ('running', 'success', 'failed')),
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  error_message text,
  created_at timestamptz not null default now()
);

create index if not exists pitcher_pitch_profiles_player_idx on public.pitcher_pitch_profiles(mlb_player_id);
create index if not exists pitcher_pitch_profiles_season_idx on public.pitcher_pitch_profiles(season);
create index if not exists pitcher_pitch_profiles_pitch_type_idx on public.pitcher_pitch_profiles(pitch_type);
create index if not exists pitcher_pitch_profiles_season_player_idx on public.pitcher_pitch_profiles(season, mlb_player_id);
create index if not exists pitcher_pitch_profiles_season_pitch_idx on public.pitcher_pitch_profiles(season, pitch_type);
create index if not exists pitcher_profiles_player_idx on public.pitcher_profiles(mlb_player_id);
create index if not exists pitcher_profiles_season_idx on public.pitcher_profiles(season);
create index if not exists pitcher_profiles_archetype_idx on public.pitcher_profiles(primary_archetype_id);
create index if not exists pitcher_profiles_model_idx on public.pitcher_profiles(model_version);
create index if not exists pitcher_profiles_season_model_idx on public.pitcher_profiles(season, model_version);
create index if not exists pitcher_archetypes_season_idx on public.pitcher_archetypes(season);
create index if not exists pitcher_archetypes_model_idx on public.pitcher_archetypes(model_version);
create index if not exists pitcher_archetypes_slug_idx on public.pitcher_archetypes(archetype_slug);
create index if not exists pitcher_archetypes_representative_idx on public.pitcher_archetypes(representative_mlb_player_id);
create index if not exists pitcher_memberships_player_idx on public.pitcher_archetype_memberships(mlb_player_id);
create index if not exists pitcher_memberships_archetype_idx on public.pitcher_archetype_memberships(archetype_id);
create index if not exists pitcher_memberships_season_idx on public.pitcher_archetype_memberships(season);
create index if not exists pitcher_memberships_model_idx on public.pitcher_archetype_memberships(model_version);
create index if not exists pitcher_memberships_primary_idx on public.pitcher_archetype_memberships(is_primary);
create index if not exists pitcher_archetype_features_archetype_idx on public.pitcher_archetype_features(archetype_id);
create index if not exists pitcher_archetype_features_model_idx on public.pitcher_archetype_features(model_version);
create index if not exists pitcher_archetype_features_rank_idx on public.pitcher_archetype_features(importance_rank);
create index if not exists pitcher_similarities_player_idx on public.pitcher_similarities(mlb_player_id);
create index if not exists pitcher_similarities_similar_player_idx on public.pitcher_similarities(similar_mlb_player_id);
create index if not exists pitcher_similarities_season_idx on public.pitcher_similarities(season);
create index if not exists pitcher_similarities_model_idx on public.pitcher_similarities(model_version);
create index if not exists pitcher_similarities_rank_idx on public.pitcher_similarities(similarity_rank);
create index if not exists pitcher_similarities_lookup_idx on public.pitcher_similarities(mlb_player_id, season, model_version, similarity_rank);
create index if not exists pitcher_model_runs_name_idx on public.pitcher_model_runs(model_name);
create index if not exists pitcher_model_runs_version_idx on public.pitcher_model_runs(model_version);
create index if not exists pitcher_model_runs_season_idx on public.pitcher_model_runs(season);
create index if not exists pitcher_model_runs_status_idx on public.pitcher_model_runs(status);
create index if not exists pitcher_model_runs_started_idx on public.pitcher_model_runs(started_at);

alter table public.pitcher_pitch_profiles enable row level security;
alter table public.pitcher_profiles enable row level security;
alter table public.pitcher_archetypes enable row level security;
alter table public.pitcher_archetype_memberships enable row level security;
alter table public.pitcher_archetype_features enable row level security;
alter table public.pitcher_similarities enable row level security;
alter table public.pitcher_model_runs enable row level security;

drop policy if exists "Allow public read pitcher pitch profiles" on public.pitcher_pitch_profiles;
create policy "Allow public read pitcher pitch profiles" on public.pitcher_pitch_profiles for select using (true);
drop policy if exists "Allow public read pitcher profiles" on public.pitcher_profiles;
create policy "Allow public read pitcher profiles" on public.pitcher_profiles for select using (true);
drop policy if exists "Allow public read pitcher archetypes" on public.pitcher_archetypes;
create policy "Allow public read pitcher archetypes" on public.pitcher_archetypes for select using (true);
drop policy if exists "Allow public read pitcher memberships" on public.pitcher_archetype_memberships;
create policy "Allow public read pitcher memberships" on public.pitcher_archetype_memberships for select using (true);
drop policy if exists "Allow public read pitcher archetype features" on public.pitcher_archetype_features;
create policy "Allow public read pitcher archetype features" on public.pitcher_archetype_features for select using (true);
drop policy if exists "Allow public read pitcher similarities" on public.pitcher_similarities;
create policy "Allow public read pitcher similarities" on public.pitcher_similarities for select using (true);
drop policy if exists "Allow public read pitcher model runs" on public.pitcher_model_runs;
create policy "Allow public read pitcher model runs" on public.pitcher_model_runs for select using (true);

create table if not exists public.batter_vs_pitcher_archetype (
  id uuid primary key default gen_random_uuid(),
  mlb_batter_id integer not null references public.dim_players(mlb_player_id),
  season integer not null,
  period_start date not null,
  period_end date not null,
  archetype_id uuid not null references public.pitcher_archetypes(archetype_id) on delete cascade,
  model_version text not null,
  feature_version text not null,
  plate_appearances integer,
  at_bats integer,
  hits integer,
  singles integer,
  doubles integer,
  triples integer,
  home_runs integer,
  walks integer,
  strikeouts integer,
  hit_by_pitch integer,
  sacrifice_flies integer,
  batting_average numeric,
  on_base_percentage numeric,
  slugging_percentage numeric,
  ops numeric,
  isolated_power numeric,
  strikeout_rate numeric,
  walk_rate numeric,
  whiff_rate numeric,
  csw_rate numeric,
  avg_exit_velocity numeric,
  hard_hit_rate numeric,
  barrel_rate numeric,
  xwoba numeric,
  woba numeric,
  run_value numeric,
  sample_quality text check (sample_quality in ('low', 'medium', 'high')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(mlb_batter_id, season, period_start, period_end, archetype_id, model_version)
);

create table if not exists public.team_vs_pitcher_archetype (
  id uuid primary key default gen_random_uuid(),
  team_abbreviation text not null references public.dim_teams(abbreviation),
  season integer not null,
  period_start date not null,
  period_end date not null,
  archetype_id uuid not null references public.pitcher_archetypes(archetype_id) on delete cascade,
  model_version text not null,
  feature_version text not null,
  plate_appearances integer,
  at_bats integer,
  hits integer,
  singles integer,
  doubles integer,
  triples integer,
  home_runs integer,
  walks integer,
  strikeouts integer,
  hit_by_pitch integer,
  sacrifice_flies integer,
  batting_average numeric,
  on_base_percentage numeric,
  slugging_percentage numeric,
  ops numeric,
  isolated_power numeric,
  strikeout_rate numeric,
  walk_rate numeric,
  whiff_rate numeric,
  csw_rate numeric,
  avg_exit_velocity numeric,
  hard_hit_rate numeric,
  barrel_rate numeric,
  xwoba numeric,
  woba numeric,
  run_value numeric,
  sample_quality text check (sample_quality in ('low', 'medium', 'high')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(team_abbreviation, season, period_start, period_end, archetype_id, model_version)
);

create index if not exists batter_archetype_batter_idx on public.batter_vs_pitcher_archetype(mlb_batter_id);
create index if not exists batter_archetype_archetype_idx on public.batter_vs_pitcher_archetype(archetype_id);
create index if not exists batter_archetype_season_idx on public.batter_vs_pitcher_archetype(season);
create index if not exists batter_archetype_model_idx on public.batter_vs_pitcher_archetype(model_version);
create index if not exists batter_archetype_season_archetype_idx on public.batter_vs_pitcher_archetype(season, archetype_id);
create index if not exists batter_archetype_lookup_idx on public.batter_vs_pitcher_archetype(mlb_batter_id, season, model_version);
create index if not exists team_archetype_team_idx on public.team_vs_pitcher_archetype(team_abbreviation);
create index if not exists team_archetype_archetype_idx on public.team_vs_pitcher_archetype(archetype_id);
create index if not exists team_archetype_season_idx on public.team_vs_pitcher_archetype(season);
create index if not exists team_archetype_model_idx on public.team_vs_pitcher_archetype(model_version);
create index if not exists team_archetype_season_archetype_idx on public.team_vs_pitcher_archetype(season, archetype_id);
create index if not exists team_archetype_lookup_idx on public.team_vs_pitcher_archetype(team_abbreviation, season, model_version);

alter table public.batter_vs_pitcher_archetype enable row level security;
alter table public.team_vs_pitcher_archetype enable row level security;
drop policy if exists "Allow public read batter archetype matchups" on public.batter_vs_pitcher_archetype;
create policy "Allow public read batter archetype matchups" on public.batter_vs_pitcher_archetype for select using (true);
drop policy if exists "Allow public read team archetype matchups" on public.team_vs_pitcher_archetype;
create policy "Allow public read team archetype matchups" on public.team_vs_pitcher_archetype for select using (true);

create table if not exists public.blog_posts (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  subtitle text,
  excerpt text,
  content text not null,
  cover_image_url text,
  author_id uuid not null references auth.users(id) on delete cascade,
  author_name text,
  status text not null default 'draft'
    check (status in ('draft', 'published')),
  tags text[] not null default '{}',
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists blog_posts_slug_idx
on public.blog_posts(slug);
create index if not exists blog_posts_status_idx
on public.blog_posts(status);
create index if not exists blog_posts_published_at_idx
on public.blog_posts(published_at desc);
create index if not exists blog_posts_author_idx
on public.blog_posts(author_id);

alter table public.blog_posts enable row level security;

drop policy if exists "Public can read published blog posts"
on public.blog_posts;
create policy "Public can read published blog posts"
on public.blog_posts
for select
using (status = 'published');

drop policy if exists "Authors can read own blog posts"
on public.blog_posts;
create policy "Authors can read own blog posts"
on public.blog_posts
for select
to authenticated
using (auth.uid() = author_id);

drop policy if exists "Authors can create blog posts"
on public.blog_posts;
create policy "Authors can create blog posts"
on public.blog_posts
for insert
to authenticated
with check (auth.uid() = author_id);

drop policy if exists "Authors can update own blog posts"
on public.blog_posts;
create policy "Authors can update own blog posts"
on public.blog_posts
for update
to authenticated
using (auth.uid() = author_id)
with check (auth.uid() = author_id);

drop policy if exists "Authors can delete own blog posts"
on public.blog_posts;
create policy "Authors can delete own blog posts"
on public.blog_posts
for delete
to authenticated
using (auth.uid() = author_id);
