import Link from "next/link";

import PageHeader from "@/components/layout/PageHeader";
import EmptyState from "@/components/ui/EmptyState";
import { listPitcherArchetypes } from "@/lib/data/pitchers";
import { createPageMetadata } from "@/lib/metadata";

export const metadata = createPageMetadata({ title: "Archetype Library | MLB Pitcher Archetypes", description: "Browse data-driven MLB pitcher archetypes built from Statcast arsenal analysis, pitch-profile features, and pitcher similarity.", path: "/pitchers/archetypes" });
const featureName = (value: string) => value.replace(/^missingindicator_/, "Missing: ").replaceAll("_", " ");
const reviewedDescription = (value: string | null) => value && !value.startsWith("A data-driven arsenal cluster") ? value : "Description pending review.";
export default async function PitcherArchetypesPage() {
  const result = await listPitcherArchetypes();
  return <div className="space-y-8">
    <div className="flex flex-wrap items-start justify-between gap-4"><PageHeader label="Pitcher Intelligence" title="Archetype Library" description="Pitchers are grouped using arsenal and pitch-profile features." /><nav className="flex gap-2 text-sm font-semibold"><Link href="/pitchers" className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-slate-700">Explorer</Link><Link href="/pitchers/map" className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-slate-700">Pitcher Map</Link></nav></div>
    <aside className="rounded-xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-slate-700">Archetype names may be model-generated placeholders unless manually reviewed. They summarize statistical clusters and should not be treated as fixed scouting classifications.</aside>
    {result.data.length ? <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{result.data.map((item) => <article key={item.archetypeId} className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-3"><h2 className="text-xl font-bold text-slate-950">{item.name}</h2><span className="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-semibold text-blue-700">{item.pitcherCount} pitchers</span></div><p className="mt-3 text-sm leading-6 text-slate-600">{reviewedDescription(item.shortDescription)}</p><p className="mt-4 text-sm text-slate-500">Representative: <span className="font-medium text-slate-700">{item.representativeName ?? "Unavailable"}</span></p><div className="mt-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Defining standardized features</p><ul className="mt-2 space-y-1 text-sm text-slate-700">{item.features.slice(0, 3).map((feature) => <li key={feature.name} className="capitalize">{featureName(feature.name)}</li>)}</ul></div><dl className="mt-4 grid grid-cols-2 gap-2 border-t border-slate-100 pt-4 text-xs text-slate-500"><div><dt>Model</dt><dd className="mt-1 font-medium text-slate-700">{item.modelVersion}</dd></div><div><dt>Features</dt><dd className="mt-1 font-medium text-slate-700">{item.featureVersion}</dd></div><div><dt>Season</dt><dd className="mt-1 font-medium text-slate-700">{item.season}</dd></div><div><dt>Silhouette</dt><dd className="mt-1 font-medium text-slate-700">{item.silhouetteScore?.toFixed(3) ?? "—"}</dd></div></dl><Link href={`/pitchers/archetypes/${item.slug}`} className="mt-5 inline-flex font-semibold text-blue-600 hover:text-blue-700">View archetype</Link></article>)}</div> : <EmptyState title={result.error ? "Pitcher archetype data is unavailable" : "No pitcher archetypes have been generated"} description="If pitcher archetype data is unavailable, run the pitcher archetype pipeline to populate this page." />}
  </div>;
}
