import type {
  BatterArchetypeMatchup,
  MatchupSort,
  TeamArchetypeMatchup,
} from "@/lib/data/archetype-matchups";

const decimal = (value: number | null, digits = 3) => value === null ? "—" : value.toFixed(digits);
const percent = (value: number | null) => value === null ? "—" : `${(value * 100).toFixed(1)}%`;
const qualityClass = { low: "bg-amber-50 text-amber-700", medium: "bg-blue-50 text-blue-700", high: "bg-emerald-50 text-emerald-700" };
const options: { value: MatchupSort; label: string }[] = [
  { value: "best_ops", label: "Best OPS" }, { value: "worst_ops", label: "Worst OPS" },
  { value: "highest_xwoba", label: "Highest xwOBA" }, { value: "lowest_strikeout", label: "Lowest strikeout rate" },
];

function SortForm({ name, value, otherName, otherValue }: { name: string; value: MatchupSort; otherName: string; otherValue: MatchupSort }) {
  return <form className="flex gap-2"><input type="hidden" name={otherName} value={otherValue} /><select name={name} defaultValue={value} aria-label={`Sort ${name === "teamSort" ? "teams" : "batters"}`} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm">{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select><button className="rounded-lg bg-slate-900 px-3 py-2 text-sm font-semibold text-white">Sort</button></form>;
}

export default function ArchetypeMatchupTables({ teams, batters, teamSort, batterSort }: { teams: TeamArchetypeMatchup[]; batters: BatterArchetypeMatchup[]; teamSort: MatchupSort; batterSort: MatchupSort }) {
  return <div className="space-y-8">
    <section className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl font-semibold text-slate-900">Teams vs This Archetype</h2><p className="mt-1 text-sm text-slate-600">Team offense aggregated against every modeled pitcher in this archetype.</p></div><SortForm name="teamSort" value={teamSort} otherName="batterSort" otherValue={batterSort} /></div>{teams.length ? <div className="mt-5 overflow-x-auto"><table className="min-w-[880px] text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-slate-600"><tr>{["Team", "PA", "OPS", "xwOBA", "K%", "BB%", "Hard-hit", "Sample"].map((heading) => <th key={heading} className="px-3 py-3 font-semibold">{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{teams.map((row) => <tr key={row.teamAbbreviation}><td className="px-3 py-3 font-semibold">{row.teamName}<span className="ml-2 text-xs text-slate-400">{row.teamAbbreviation}</span></td><td className="px-3 py-3">{row.plateAppearances}</td><td className="px-3 py-3">{decimal(row.ops)}</td><td className="px-3 py-3">{decimal(row.xwoba)}</td><td className="px-3 py-3">{percent(row.strikeoutRate)}</td><td className="px-3 py-3">{percent(row.walkRate)}</td><td className="px-3 py-3">{percent(row.hardHitRate)}</td><td className="px-3 py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold capitalize ${qualityClass[row.sampleQuality]}`}>{row.sampleQuality}</span></td></tr>)}</tbody></table></div> : <p className="mt-5 rounded-lg border border-dashed border-slate-300 p-6 text-center text-sm text-slate-600">Team matchup data is not available for this archetype yet.</p>}</section>
    <section className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl font-semibold text-slate-900">Batters vs This Archetype</h2><p className="mt-1 text-sm text-slate-600">Individual results are descriptive and can be noisy in limited samples.</p></div><SortForm name="batterSort" value={batterSort} otherName="teamSort" otherValue={teamSort} /></div>{batters.length ? <div className="mt-5 overflow-x-auto"><table className="min-w-[900px] text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-slate-600"><tr>{["Batter", "Team", "PA", "OPS", "xwOBA", "HR", "K%", "BB%", "Sample"].map((heading) => <th key={heading} className="px-3 py-3 font-semibold">{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{batters.map((row) => <tr key={row.mlbBatterId}><td className="px-3 py-3 font-semibold">{row.fullName}</td><td className="px-3 py-3">{row.teamAbbreviation ?? "—"}</td><td className="px-3 py-3">{row.plateAppearances}</td><td className="px-3 py-3">{decimal(row.ops)}</td><td className="px-3 py-3">{decimal(row.xwoba)}</td><td className="px-3 py-3">{row.homeRuns}</td><td className="px-3 py-3">{percent(row.strikeoutRate)}</td><td className="px-3 py-3">{percent(row.walkRate)}</td><td className="px-3 py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold capitalize ${qualityClass[row.sampleQuality]}`}>{row.sampleQuality}</span></td></tr>)}</tbody></table></div> : <p className="mt-5 rounded-lg border border-dashed border-slate-300 p-6 text-center text-sm text-slate-600">Batter matchup data is not available for this archetype yet.</p>}</section>
    <aside className="rounded-xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-slate-700">Small matchup samples are descriptive, not predictive. “Low” and “medium” quality rows should be interpreted cautiously, and even “high” quality does not isolate park, count, handedness, pitcher quality, or era effects.</aside>
  </div>;
}
