import Link from "next/link";

import type { ArchetypeMatchupSummary as Summary } from "@/lib/data/archetype-matchups";

const decimal = (value: number | null) => value === null ? "—" : value.toFixed(3);

export default function ArchetypeMatchupSummary({ summary, archetypeSlug }: { summary: Summary; archetypeSlug: string | null }) {
  return <div className="grid gap-6 lg:grid-cols-2"><div><h3 className="text-sm font-semibold uppercase tracking-wide text-slate-500">Top team results</h3>{summary.teams.length ? <ul className="mt-3 space-y-2">{summary.teams.slice(0, 3).map((team) => <li key={team.teamAbbreviation} className="flex items-center justify-between rounded-lg border border-slate-200 px-4 py-3"><span className="font-semibold text-slate-800">{team.teamAbbreviation}<span className="ml-2 text-xs font-normal text-slate-500">{team.plateAppearances} PA · {team.sampleQuality}</span></span><span className="font-semibold">{decimal(team.ops)} OPS</span></li>)}</ul> : <p className="mt-3 text-sm text-slate-600">No team matchup rows are available.</p>}</div><div><h3 className="text-sm font-semibold uppercase tracking-wide text-slate-500">Top batter results</h3>{summary.batters.length ? <ul className="mt-3 space-y-2">{summary.batters.slice(0, 3).map((batter) => <li key={batter.mlbBatterId} className="flex items-center justify-between rounded-lg border border-slate-200 px-4 py-3"><span className="font-semibold text-slate-800">{batter.fullName}<span className="ml-2 text-xs font-normal text-slate-500">{batter.plateAppearances} PA · {batter.sampleQuality}</span></span><span className="font-semibold">{decimal(batter.ops)} OPS</span></li>)}</ul> : <p className="mt-3 text-sm text-slate-600">No batter matchup rows are available.</p>}</div>{archetypeSlug ? <Link href={`/pitchers/archetypes/${archetypeSlug}#matchup-intelligence`} className="font-semibold text-blue-600 hover:text-blue-700 lg:col-span-2">View complete archetype matchup intelligence</Link> : null}</div>;
}
