import Link from "next/link";

import type { StarterArchetypeMatchup } from "@/lib/data/archetype-matchups";

const rate = (value: number | null) => value === null ? "—" : `${(value * 100).toFixed(1)}%`;
const decimal = (value: number | null) => value === null ? "—" : value.toFixed(3);

export default function StarterArchetypeMatchups({ rows }: { rows: StarterArchetypeMatchup[] }) {
  return <section className="mt-8" aria-labelledby="archetype-matchups-heading"><div className="mb-5"><h2 id="archetype-matchups-heading" className="text-xl font-semibold text-slate-900">Archetype Matchup Intelligence</h2><p className="mt-1 text-sm text-slate-600">Optional context for expected starters; existing Scouting Report calculations are unchanged.</p></div>{rows.length ? <div className="grid gap-4 md:grid-cols-2">{rows.map((row) => <article key={`${row.mlbPlayerId}-${row.opponentAbbreviation}`} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><p className="font-semibold text-slate-950">{row.pitcherName}</p><Link href={`/pitchers/archetypes/${row.archetypeSlug}`} className="mt-1 inline-flex text-sm font-semibold text-blue-600">{row.archetypeName}</Link><p className="mt-3 text-sm text-slate-600">{row.opponentAbbreviation} offense vs this archetype</p>{row.teamPerformance ? <dl className="mt-3 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-slate-500">OPS</dt><dd className="font-semibold">{decimal(row.teamPerformance.ops)}</dd></div><div><dt className="text-slate-500">xwOBA</dt><dd className="font-semibold">{decimal(row.teamPerformance.xwoba)}</dd></div><div><dt className="text-slate-500">K%</dt><dd className="font-semibold">{rate(row.teamPerformance.strikeoutRate)}</dd></div><div><dt className="text-slate-500">BB%</dt><dd className="font-semibold">{rate(row.teamPerformance.walkRate)}</dd></div><div className="col-span-2"><dt className="text-slate-500">Sample</dt><dd className="font-semibold capitalize">{row.teamPerformance.sampleQuality} · {row.teamPerformance.plateAppearances} PA</dd></div></dl> : <p className="mt-3 rounded-lg bg-slate-50 p-3 text-sm text-slate-600">Archetype matchup data is not available yet for this starter.</p>}</article>)}</div> : <p className="rounded-xl border border-dashed border-slate-300 bg-white p-6 text-center text-sm text-slate-600">Archetype matchup data is not available yet for this starter.</p>}</section>;
}
